export const colors = {
  light: {
    background: '#FFFFFF',
    text: '#1B4332',
    primary: '#2D6A4F',
    card: '#F5F5F5',
    button: '#40916C',
    placeholderColor: '#888',
    selectedTextColor: '#333',
    container: '#fff',
    borderColor: '#ccc',
    colorError: 'red',
    buttonText: '#fff',
    inputColor:'#333',
  },
  dark: {
    background: '#0B1110',
    text: '#D8F3DC',
    primary: '#2D6A4F',
    card: '#1B4332',
    button: '#52B788',
    placeholderColor: '#888',
    selectedTextColor: '#333',
    container: '#fff',
    borderColor: '#ccc',
    colorError: 'red',
    buttonText: '#fff',
    inputColor:'#fff',
  },
};
